version: '3'

services:
  porter-http:
    restart: on-failure
    image: porter:latest
    container_name: porter-http
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      # Default Porter port
      - "80:9155"
    volumes:
      - .:/code
      - ~/.local/share/nucypher:/nucypher
    command: ["nucypher-porter", "run",
              "--eth-provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}",
              "--allow-origins", "${PORTER_CORS_ALLOW_ORIGINS}"]  # empty string if env var not defined which translates to CORS not enabled by default
